### ISSUE TITLE
Ch 1 - Introduction to MLOps

### ISSUE THREAD

**Issue by neverforgit** [mlopscommunity/Reading-Group-Practical-MLOps#1]

**Comment by SommerChase** [comment]
If anyone has a problem running `make test` on page 12, try changing `python` to `python3` on line 23.

It was giving me an error, but changing python to python3 worked :)

**Comment by SommerChase** [comment]
For those new to **Makefile** (like me),[ this article](https://medium.com/analytics-vidhya/makefile-make-rules-and-automate-in-python-982a41c99275#:~:text=%20How%20to%20use%20MakeFile%20in%20Python%3A%20,9%20Run%20Test%20commands%20like%20PyTest%20More%20) was helpful for getting a general idea.

To sum it up: "Basically, we have automated all manual terminal work ... in **MakeFile**"

**Comment by SommerChase** [comment]
**Configuring Continuous Integration with GitHub Actions** Page: 13

After pushing code to GitHub and running the workflows in GitHub Actions, the AWS Amazon Linux 2 3.7.9 job failed. It's actually failed 3 times for me.

After searching [Github-hosted runners docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners), I couldn't find `amazonlinux ` as a supported virtual machine. Could someone help me understand whether I am crazy or not?

**Comment by eduardobonet** [comment]
@SommerChase there's a repo with examples, perhaps you can find the solution there? https://github.com/noahgift/github-actions-demo/tree/main/.github/workflows

**Comment by eduardobonet** [comment]
The author mentioned a few best practices on DevOps: CI/CD, Microservices, IaC, monitoring, effective technical communication and effective technical management. The one I don't agree with is `Microservices`:  for a while it was hyped, but by no means it's a best practice. It can be for larger teams, but for smaller teams microservices add a lot of overhead which go against the DevOps idea. But that begs the question, we often see the stack for ML continuous delivery solutions in a microservice setup, wrapped by APIs, but what would they look like when they need to be part of the main application?
